USE [master]
GO

/****** Object:  Database [lyicsdb]    Script Date: 3/29/2016 6:21:09 PM ******/
EXEC msdb.dbo.sp_delete_database_backuphistory @database_name = N'lyicsdb'
GO
USE [master]
GO
ALTER DATABASE [lyicsdb] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
USE [master]
GO
/****** Object:  Database [lyicsdb]    Script Date: 3/29/2016 6:29:53 PM ******/
DROP DATABASE [lyicsdb]
GO


/****** Object:  Database [lyicsdb]    Script Date: 3/29/2016 6:21:09 PM ******/
CREATE DATABASE [lyicsdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'lyicsdb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\lyicsdb.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'lyicsdb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\lyicsdb_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [lyicsdb] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [lyicsdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [lyicsdb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [lyicsdb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [lyicsdb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [lyicsdb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [lyicsdb] SET ARITHABORT OFF 
GO

ALTER DATABASE [lyicsdb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [lyicsdb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [lyicsdb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [lyicsdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [lyicsdb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [lyicsdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [lyicsdb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [lyicsdb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [lyicsdb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [lyicsdb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [lyicsdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [lyicsdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [lyicsdb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [lyicsdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [lyicsdb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [lyicsdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [lyicsdb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [lyicsdb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [lyicsdb] SET  MULTI_USER 
GO

ALTER DATABASE [lyicsdb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [lyicsdb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [lyicsdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [lyicsdb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [lyicsdb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [lyicsdb] SET  READ_WRITE 
GO


